### ISSUE TITLE
How to get url and token for create client

### ISSUE THREAD

**Issue by sunilyadavacs** [chatapi/whatsApp-php#1]
How to get url and token for create client

**Comment by Tamidin** [comment]
You can try demo on https://chat-api.com

**Comment by sunilyadavacs** [comment]
Demo is not working, didn't get 3 day trial , only payment page is working 
I think Its Fake

**Comment by NikiCage** [comment]
Is not Fake. Demo is working. Demos are issued in limited quantities on registration. Perhaps the problem is this. Write sale@chat-api.com and ask for a demo. You will be given a free period
